Replace $# with $*, as cited by @tricantivu

diff --git a/jbuild b/jbuild
--- a/jbuild
+++ b/jbuild
@@ -231,17 +231,12 @@ while [[ $# -gt 0 ]]; do
             exit 0
         ;;
         -\? | --?)
-            echo "Invalid option: -$#" >&2
-            usage
-            exit 1
-        ;;
-        :)
-            echo "Option -$# requires an argument." >&2
+            echo "Invalid option: -$*" >&2
             usage
             exit 1
         ;;
         *)
-            echo "Invalid option: -$#" >&2
+            echo "Invalid option: -$*" >&2
             usage
             exit 1
         ;;
