Call function to show errors

diff --git a/jbuild b/jbuild
--- a/jbuild
+++ b/jbuild
@@ -11,8 +11,9 @@ SOURCE="archlive"
 LIVEROOT="airootfs"
 CONFIG="jovarkos-config"
 
-function generic_error() {
-    echo "Incorrect syntax or options. Please use the 'help' flag for more information."
+function error() {
+
+    printf "$*\n" >&2
 }
 
 function error_no-archiso() {
@@ -151,12 +152,12 @@ while getopts ":br:p:hv" opt; do
             version
         ;;
         (:)
-            echo "Option -$OPTARG requires an argument." >&2
+            error "Option -$OPTARG requires an argument."
 
             exit 1
         ;;
         ('?')
-            echo "Invalid option: -$OPTARG" >&2
+            error "Invalid option: -$OPTARG"
 
             exit 1
         ;;
