Replace commands to check dependencies

diff --git a/jbuild b/jbuild
--- a/jbuild
+++ b/jbuild
@@ -33,11 +33,6 @@ function clean () {
     sudo rm -rf ${WORKING}
 }
 
-function no_mkarchiso () {
-    error "mkarchiso is not installed. Please install it and try again."
-    exit 1
-}
-
 function build_iso() {
     no_archiso_dir
     echo "Clearing ${WORKING} directory before beginning..."
@@ -161,26 +156,20 @@ USAGE
 version
 }
 
-if ! command -v mkarchiso &> /dev/null; then
-    error "mkarchiso is not installed. Please install it and try again."
-cat << ERROR
-To install mkarchiso:
-    sudo pacman -S mkarchiso
-ERROR
-    exit 1
-fi
+m=0
 
+for dep in make mkarchiso; do
+    type -P "${dep}" &> /dev/null || {
 
-if ! command -v make &> /dev/null; then
-    error "make is not installed. Please install it and try again."
-cat << ERROR
-To install mkarchiso:
-    sudo pacman -S make
-ERROR
-    exit 1
-fi
+        error "${dep} is not installed. Please install it and try again."
 
+        # Count missing dependencies
+        (( m++ ))
+    }
+done
 
+# Fail when one or more are missing
+(( m )) && exit 1
 
 # Parse command-line options and arguments, send to functions as needed
 while [[ $# -gt 0 ]]; do
